name: cryptid
description: "Cryptid"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.6
  cupertino_icons: ^1.0.8
  package_info_plus: ^8.0.2
  encrypt: ^5.0.3
  crypto: ^3.0.5
  shared_preferences: ^2.3.2
  file_picker: ^8.1.2
  path_provider: ^2.1.4
  url_launcher: ^6.3.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/github.svg
    - assets/logo.svg